YamlReader: get file content before parsing
semaio/Magento2-ConfigImportExport pull request #29
Opened 2018-08-31 09:51 UTC by mwr

With Symfony Yaml >= 3.0 the option to pass a filename was removed. 
The commit 6c959b8c56a9e027e2f3727cc9719681e1fe2f8e introduces the compatibilty with >=3.0.

To support 2.0 and 3.0 of Symfony Yaml we need get the file contents in the YamlReader.

Also see:
Yaml.php @ v2.8 https://github.com/symfony/yaml/blob/2.8/Yaml.php#L58
Yaml.php @ v3.3 https://github.com/symfony/yaml/blob/3.3/Yaml.php#L52

The ``file_get_contents`` is no longer there.

Please make sure these boxes are checked before submitting your PR - thank you!

- [ ] Pull request is based against develop branch
- [ ] README.md reflects changes (if applicable)
- [ ] New files contain a license header

### Issue

This PR fixes issue # .

### Proposed changes

...

2018-09-03 11:32 UTC, ktomk requested changes
The code is only against the happy path and misses to handle the error case of the file_get_contents() call.

Also I'm not against seeing some unit tests covering the change.

2018-09-03 11:32 UTC, ktomk commented on Model/File/Reader/YamlReader.php
> +        $content = SymfonyYaml::parse(file_get_contents($fileName));
file_get_contents returns FALSE on error but SymfonyYaml::parse()  must be called w/ a string parameter.

2018-09-03 11:35 UTC, ktomk commented
@mwr Thanks for the PR I started a quick review, it's merely some minor annoyance. If you see yourself able to do, please add a test or two.

2019-02-24 12:40 UTC, ktomk commented
@mwr  Thanks for the update. Please squash and polish this PR's changes and messages.

And there was a lot of changes regarding the composer.json file, can you share the rationale of the final selection? That would be great to ease the review.

2019-11-01 09:02 UTC, DavidLambauer commented
Is it possible to just merge this, please? 🤷‍♂

2020-03-05 20:37 UTC, DavidLambauer commented
Can be closed as it is already fixed in develop.

2020-03-05 20:37 UTC, closed without merging